spring.datasource.url=${DB_URL:jdbc:mysql://junction.proxy.rlwy.net:16666/railway}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:ILYtLfEqEsXMNuJnCfMbMkVTnEzNqoAg}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true